# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: projeto02.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'projeto02.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprojeto02.proto\x12\tprojeto02\"?\n\nDescoberta\x12\x19\n\x11inicia_descoberta\x18\x01 \x01(\x08\x12\x16\n\x0eporta_resposta\x18\x02 \x01(\x05\"\x9b\x01\n\x08Resposta\x12+\n\x06sensor\x18\x01 \x01(\x0b\x32\x19.projeto02.RespostaSensorH\x00\x12-\n\x07\x61tuador\x18\x02 \x01(\x0b\x32\x1a.projeto02.RespostaAtuadorH\x00\x12+\n\x07leitura\x18\x03 \x01(\x0b\x32\x18.projeto02.LeituraSensorH\x00\x42\x06\n\x04tipo\"E\n\x0eRespostaSensor\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05porta\x18\x04 \x01(\x05\"^\n\x0fRespostaAtuador\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\r\n\x05porta\x18\x04 \x01(\x05\x12\x16\n\x0e\x65stado_inicial\x18\x05 \x01(\x08\"=\n\rLeituraSensor\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"D\n\rStatusAtuador\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x65stado_atual\x18\x02 \x01(\x08\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"C\n\x07\x43omando\x12\x0f\n\x07id_alvo\x18\x01 \x01(\t\x12\x14\n\x0ctipo_comando\x18\x02 \x01(\t\x12\x11\n\tparametro\x18\x03 \x01(\x02\"@\n\x0fRespostaComando\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\x12\x10\n\x08mensagem\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'projeto02_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DESCOBERTA']._serialized_start=30
  _globals['_DESCOBERTA']._serialized_end=93
  _globals['_RESPOSTA']._serialized_start=96
  _globals['_RESPOSTA']._serialized_end=251
  _globals['_RESPOSTASENSOR']._serialized_start=253
  _globals['_RESPOSTASENSOR']._serialized_end=322
  _globals['_RESPOSTAATUADOR']._serialized_start=324
  _globals['_RESPOSTAATUADOR']._serialized_end=418
  _globals['_LEITURASENSOR']._serialized_start=420
  _globals['_LEITURASENSOR']._serialized_end=481
  _globals['_STATUSATUADOR']._serialized_start=483
  _globals['_STATUSATUADOR']._serialized_end=551
  _globals['_COMANDO']._serialized_start=553
  _globals['_COMANDO']._serialized_end=620
  _globals['_RESPOSTACOMANDO']._serialized_start=622
  _globals['_RESPOSTACOMANDO']._serialized_end=686
# @@protoc_insertion_point(module_scope)
